name: jacknadar
favicon: null
layout_spectrum: 0.91327
typography_spectrum: 0.44254
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#161415'
    - '#47423f'
    - '#ada69e'
    - '#686a67'
  brandStrength: 0.9375
  lightness: 0.5975268613547087
  saturation: 0.5255994386970997
  rhythmicContrast: 0.5338622904382646
purpose: []
