name: jacknadar
favicon: null
layout_spectrum: 0.6110502248629928
typography_spectrum: 0.20066366042010486
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9430841815192252
  lightness: 0.5975268613547087
  saturation: 0.5255994386970997
  rhythmicContrast: 0.5338622904382646
purpose: []
